-- Run this once in the Supabase SQL Editor.
-- NOOR Classes inquiries are intentionally not readable by the public client.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  mode text not null,
  studentName text not null,
  grade integer not null,
  board text not null,
  school text,
  currentScore text,
  targetScore text,
  subjects jsonb not null default '[]'::jsonb,
  goals jsonb not null default '[]'::jsonb,
  address text,
  sector text,
  city text not null,
  country text,
  timezone text,
  frequency text not null,
  preferredTime text not null,
  parentName text not null,
  whatsapp text not null,
  phone text not null,
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

-- No anonymous SELECT/INSERT/UPDATE/DELETE policies are created.
-- The Next.js server route writes with SUPABASE_SERVICE_ROLE_KEY, which must
-- remain a server-only Vercel environment variable and must never use NEXT_PUBLIC_.

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiries_phone_idx on public.inquiries (phone);
